### ISSUE TITLE
Needs reproducible install

### ISSUE THREAD

**Issue by jcorbin** [kivutar/permadev#1]
# First: cheers

This is exactly the sort of game I'm lieu to loose way too much time playing; the fact that the game is currently unplayable has likely saved me from myself, at least for the short term...

# The Problem

Not being a regular python game developer, I'm unable to run `main.py`... missing tcod...

Okay, I've got this, I used to be a python developer... so I need a virtualenv, rather than just installing things into user or system libraries...

Okay, guess I'll use pipenv, and start adding dependencies...

But after a `pipenv install tcod`, I squarely landed on a dynamic linker error circa SDL:
```shell
(permadev) $ python main.py
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import tcod
  File "/Users/jcorbin/.local/share/virtualenvs/permadev-6A3-Fb89/lib/python3.8/site-packages/tcod/__init__.py", line 21, in <module>
    from tcod import (
  File "/Users/jcorbin/.local/share/virtualenvs/permadev-6A3-Fb89/lib/python3.8/site-packages/tcod/bsp.py", line 28, in <module>
    import tcod.random
  File "/Users/jcorbin/.local/share/virtualenvs/permadev-6A3-Fb89/lib/python3.8/site-packages/tcod/random.py", line 13, in <module>
    import tcod.constants
  File "/Users/jcorbin/.local/share/virtualenvs/permadev-6A3-Fb89/lib/python3.8/site-packages/tcod/constants.py", line 6, in <module>
    from tcod.color import Color
  File "/Users/jcorbin/.local/share/virtualenvs/permadev-6A3-Fb89/lib/python3.8/site-packages/tcod/color.py", line 7, in <module>
    from tcod._internal import deprecate
  File "/Users/jcorbin/.local/share/virtualenvs/permadev-6A3-Fb89/lib/python3.8/site-packages/tcod/_internal.py", line 10, in <module>
    from tcod.loader import ffi, lib
  File "/Users/jcorbin/.local/share/virtualenvs/permadev-6A3-Fb89/lib/python3.8/site-packages/tcod/loader.py", line 92, in <module>
    from tcod._libtcod import ffi, lib  # type: ignore # noqa: F401
ImportError: dlopen(/Users/jcorbin/.local/share/virtualenvs/permadev-6A3-Fb89/lib/python3.8/site-packages/tcod/_libtcod.abi3.so, 2): Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2
  Referenced from: /Users/jcorbin/.local/share/virtualenvs/permadev-6A3-Fb89/lib/python3.8/site-packages/tcod/_libtcod.abi3.so
  Reason: image not found
```

# Request

- please at least add a readme with some kind of install instructions
- at least add a requirements.txt listing what libraries are needed
- ideally use something like [pipenv](https://pypi.org/project/pipenv/) that will record a lock file of exactly what version you're using of everything (and what versions they dependencies are at)
- otherwise, any user, or even yourself in the future, may have a hard time setting up a working set of dependencies

Whatever you end up with, test out those instructions: try to follow those instructions inside a fresh system, or at least, a fresh user account.

**Comment by HexDecimal** [comment]
This could be a specific issue with `tcod` on MacOS rather than this project.  Installing the SDL2.framework globally might fix this problem temporarily.

I 2nd adding a `requirements.txt` file.  Is is a basic step for any collaborative Python project.

**Comment by finchco** [comment]
I'm on macOS 11, and did:

`pip3 install tcod
`
`python3 main.py
`

and it worked.

**Comment by HexDecimal** [comment]
To be clear this is sensitive to the version you're using.  Anything before macOS 10.9 is expected to trigger the issue.  Any non-x64 architecture would also be a problem.

**Comment by jcorbin** [comment]
> To be clear this is sensitive to the version you're using. Anything before macOS 10.9 is expected to trigger the issue. Any non-x64 architecture would also be a problem.

fwiw, I'm on an x64 MBP running macOS 11.2.3 ; maybe my issue had to do with trying to use a virtualenv, rather than a global install of tcod? dunno, never used tcod (directly at least) before

**Comment by HexDecimal** [comment]
It should work as long as the `tcod-12.0.0-cp36-abi3-macosx_10_9_x86_64.whl` wheel is used.  It won't matter where it's installed as long as it wasn't installed from source.

On MacOS `tcod` has a extra preparation step where SDL gets bundled into the wheel.  This step is skipped when it's installed from source.  A `Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2` error might be an indication that this happened since the install name is supposed to be modified to `@rpath/SDL2`.

There's also a chance that the latest version of `tcod` is plain broken and that you might be able to get an easier version working.  MacOS is the most difficult platform to support.

**Comment by kivutar** [comment]
Hi, for me,

```
pip3 install tcod
python3 main.py
```

was enough, will add it in the readme.

Don't worry about loosing your life in the game, it's not even a full demo :)
